### ISSUE TITLE
What will be our KPIs??

### ISSUE THREAD

**Issue by Abdullahdaeej** [profmasson/IINF.496-596.F2015#27]
based on our last meeting we had:

1- the number of user
2- the number of likes
3- average time spent to commit a change.

What else??

**Comment by Lauren367** [comment]
If its been shared by anyone so others can see.

**Comment by hagyoungbyoun** [comment]
I've added two indicators: public knowledge (reputation) of the community for measuring the effectiveness of the marketing strategies, and average time between release dates of new versions for measuring punctuality of the teams.

**Comment by ksaroop** [comment]
For key performance indicators,

If we want to measure the popularity and success of the community and company, we should create a separate forum for our consumers so that they could meet other gamers like themselves and exchange information. Furthermore, we could use that discussion board to ask them for suggestions on features for any future versions that might be released. This might also support the success of our marketing campaign if we can get clients to invest in our game even when they are not playing it. What do you guys think?

Also, are there any sections that need to be created, need further elaboration or any added information to it? I'll go over most of the document tonight to look for any grammar mistakes and improve clarity where I can.

**Comment by ksaroop** [comment]
Also,

for the "build a community wider to our goals section"

would it be approriate to add promotional materials that are based on online activities. I was thinking about how Call of Duty has double XP weekend and stuff like that and since the gaming program would be online, it would be fitting to mention something like that. I write 2 or three sentences and add it to that section. what do you guys think?

**Comment by Abdullahdaeej** [comment]
excellent point @ksaroop

**Comment by Abdullahdaeej** [comment]
@ksaroop for KPI number 4, can we say "the number of followers" or "number of post that used the community Hash"
something that are countable , so we can measure the public knowledge.

**Comment by Cbeni** [comment]
I was doing some research on KPI's that we could track, and these were the most popular ones among small businesses and startups (listed below). So to measure the number of people who used the community hashtag we could measure number 2 on my list? What do you guys think? 
1. Website traffic

2.Social media reach and engagement 
3. Email marketing performance 
4. Sales growth

**Comment by robzakharchuk66** [comment]
We can use google analytics to track website traffic. It's a free tool, would be great for our startup when money is tight.

Sent from my iPhone

On Dec 17, 2015, at 7:29 AM, CBenitez <notifications@github.com<mailto:notifications@github.com>> wrote:

I was doing some research on KPI's that we could track, and these were the most popular ones among small businesses and startups (listed below). So to measure the number of people who used the community hashtag we could measure number 2 on my list? What do you guys think?
1.  Website traffic 2.Social media reach and engagement
2.  Email marketing performance
3.  Sales growth

##

**Comment by ahussain6** [comment]
I agree with Rob, I like the google analytics idea. It would be good for us especially as a start up to make sure our information reaches the right people.

On Dec 17, 2015, at 7:39 AM, robzakharchuk66 <notifications@github.com<mailto:notifications@github.com>> wrote:

We can use google analytics to track website traffic. It's a free tool, would be great for our startup when money is tight.

Sent from my iPhone

On Dec 17, 2015, at 7:29 AM, CBenitez <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:

I was doing some research on KPI's that we could track, and these were the most popular ones among small businesses and startups (listed below). So to measure the number of people who used the community hashtag we could measure number 2 on my list? What do you guys think?
1. Website traffic 2.Social media reach and engagement
2. Email marketing performance
3. Sales growth

## 

Reply to this email directly or view it on GitHubhttps://github.com/profmasson/IINF.496-596.F2015/issues/27#issuecomment-165440010.

##

**Comment by ksaroop** [comment]
I highly agree with the Google Analytics implementation because it also shows how people have reached our website. From this analysis, we could learn which referrals and promotional awareness has worked. The google analytics would show us who found us through google, who typed our website in directly and from what sites people reached ours. I think there is also a function for social media with similar capabilities in the plugin so we can use that also to analyze traffic. 

Sales growth could probably be measured using Excel and then creating visual graphs and charts to make it easier to see if we are increasing or declining in sales.

**Comment by ksaroop** [comment]
@Abdullahdaeej exactly. Those would be two great metrics to use when analyzing the knowledge and interest that people have in the project.

**Comment by Abdullahdaeej** [comment]
Excellent observation.  So, let use Google Analytic as a tool to measure the website traffic, which also indicate the success of our marketing campaign.

**Comment by Abdullahdaeej** [comment]
great suggestion @ahussain6   i think we can use number 1 &2 
 KPI 1 can be measured via googel analytic tool
 KPI 2 would be measured as you mention through the number of participation in community hashtag and other social media channels.

**Comment by rafaelleitao** [comment]
I agree with the use of google analytics because it by itself is a really good way to assess the performance of the coverage and effectiveness of the marketing work of the company.
